spring:
  application:
    name: ForoHub

  datasource:
    url: jdbc:mysql://${DB_HOST}/foro_hub?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # show stack trace and format sql details
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # deshabilitas la apertura del contexto de persistencia en la capa de vista
    open-in-view: false

#reducirá el nivel de detalle de los logs relacionados con Hibernate y HikariCP
logging:
  level:
    org:
      hibernate: warn
    com:
      zaxxer:
        hikari: warn

# prevent the exception stack tracer
server:
  error:
    include-stacktrace: never

  servlet:
    context-path: /api